// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwvcxowyoisfkemssmkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3dmN4b3d5b2lzZmtlbXNzbWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzI4NzEsImV4cCI6MjA1ODQwODg3MX0.tKH6qce6JMdPWrDIH8zxzaAjn8O0PDHc8lujbWQn4Ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);